### ISSUE TITLE
beta5发布了，能不能更新一下composer。

### ISSUE THREAD

**Issue by Poordeveloper** [Flarum-Chinese/flarum-ext-simplified-chinese#14]
谢谢

**Comment by phoenixlzx** [comment]
在论坛目录下执行 `composer require jsthon/flarum-ext-simplified-chinese`

然后修改 `vendor/jsthon/flarum-ext-simplified-chinese/bootstrap.php` 为[这个版本](https://github.com/flarum/flarum-ext-english/blob/e8d8d5de6d1ba50deb284e4fbf296e388e5f54db/bootstrap.php)

也请 @jsthon 来更新下这个文件。

**Comment by jsthon** [comment]
收到！
