### ISSUE TITLE
帮忙修改了一些翻译

### ISSUE THREAD

**Issue by ExerciseBook** [Flarum-Chinese/flarum-ext-simplified-chinese#22]
![File](https://cloud.githubusercontent.com/assets/6327311/22055740/98abe44c-dd97-11e6-90ca-0744c65a19e0.jpg)
修改↑上图扩展名为zip即可解压。

我改了一些翻译的内容，希望可以帮助更多的人来理解这个汉化吧。

P.S.
	邮件相关的没有改动
	举报(Report) 相关由部分文字没有成功显示出来所以无法确定我的翻译是否准确。

**Comment by ExerciseBook** [comment]
`    # These translations are used in the Extensions page.
    extensions:
      add_button: 添加插件
      disable_button: 停用
      enable_button: 启用
      settings_button: 设置
      uninstall_button: 卸载`
 
这里有所改动，望库主知晓。

原文是
`      settings_button: => core.ref.settings`

但 core.ref.settings 被我改成了“个人设置”（为了与菜单中的其他字符对齐，都是四个字看起来更舒服）所以在这里需要修改成独立的另外的字段。

**Comment by jsthon** [comment]
已更新 v0.1.0-beta.7
